In [1]:
import numpy as np
import torch

In [2]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [12]:
s = a.sum()
s

tensor(6)

In [13]:
a = torch.FloatTensor([2,3])

In [16]:
ca = a.cuda(); ca

tensor([2., 3.], device='cuda:0')

In [17]:
ca + 1

tensor([3., 4.], device='cuda:0')

In [24]:
ca.requires_grad

False

In [53]:
v1 = torch.tensor([1.0, 1.0], requires_grad=True)
v2 = torch.tensor([2.0, 2.0])

In [54]:
v_sum = v1 + v2
v_res = (v_sum*2).sum()
v_res

tensor(12., grad_fn=<SumBackward0>)

In [55]:
for v in [v1, v2, v_sum, v_res]:
    print(v, v.is_leaf)

tensor([1., 1.], requires_grad=True) True
tensor([2., 2.]) True
tensor([3., 3.], grad_fn=<AddBackward0>) False
tensor(12., grad_fn=<SumBackward0>) False


In [56]:
for v in [v1, v2, v_sum, v_res]:
    print(v, v.requires_grad)

tensor([1., 1.], requires_grad=True) True
tensor([2., 2.]) False
tensor([3., 3.], grad_fn=<AddBackward0>) True
tensor(12., grad_fn=<SumBackward0>) True


In [60]:
v_res

tensor(12., grad_fn=<SumBackward0>)

In [63]:
v1.grad

tensor([2., 2.])

In [64]:
from torch import nn
l = nn.Linear(2, 5)

In [66]:
l

Linear(in_features=2, out_features=5, bias=True)

In [71]:
v = torch.tensor([1, 2], dtype=torch.float32)

In [72]:
v

tensor([1., 2.])

In [74]:
l(v)

tensor([-0.3548,  0.2800, -1.0179, -1.1196, -0.1165], grad_fn=<AddBackward0>)

In [76]:
list(l.parameters())

[Parameter containing:
 tensor([[-0.1143, -0.3341],
         [ 0.6768, -0.1457],
         [-0.6238, -0.0930],
         [ 0.3323, -0.5952],
         [-0.2654,  0.3490]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4276, -0.1055, -0.2081, -0.2614, -0.5491], requires_grad=True)]

In [78]:
l.state_dict()

OrderedDict([('weight',
              tensor([[-0.1143, -0.3341],
                      [ 0.6768, -0.1457],
                      [-0.6238, -0.0930],
                      [ 0.3323, -0.5952],
                      [-0.2654,  0.3490]])),
             ('bias', tensor([ 0.4276, -0.1055, -0.2081, -0.2614, -0.5491]))])

In [79]:
s = nn.Sequential(
    nn.Linear(2, 5),
    nn.ReLU(),
    nn.Linear(5, 20),
    nn.ReLU(),
    nn.Linear(20, 10),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1)
)

In [85]:
s(torch.FloatTensor([[1, 2]]))

tensor([[0.0917, 0.1499, 0.0968, 0.0896, 0.1068, 0.0790, 0.0800, 0.0858, 0.0968,
         0.1236]], grad_fn=<SoftmaxBackward>)